_inputs:
  image:
    type: file
    options:
      uploads_dir: uploads
      accepts_mime_types: image/gif,image/jpeg,image/png,image/webp,image/svg+xml
      # width: 1600
      # height: 1200
collections_config:
  images:
    icon: image
    filter:
      exclude:
        - images.json
    _enabled_editors:
      - data
    schemas:
      default:
        path: src/_schemas/images.md
