collections_config:
  images:
    icon: image
    filter:
      exclude:
        - images/images.json
    _enabled_editors:
      - data
    schemas:
      default:
        path: src/_schemas/images.md
